-- Generated by LuaSTG
-- Mod name: Boss Rush
---@author 吃药图书
_editor_class = {}
_editor_boss = {}
_sc_table = {}
---有点复杂的表
---这里直接写一写
---_sc_pr_table = {{{
---sc_group = {{card = @boss.card, boss = @boss} ,... },
---CardName = @string,
---index = @number}, ... } ,... }
_sc_pr_table = {}
_infinite = 4294967296



DoFile('mod\\BackGroundLoading.lua')

ColorList = { { 250, 128, 114 },
              { 218, 112, 214 },
              { 135, 206, 235 },
              { 127, 255, 212 },
              { 189, 252, 201 },
              { 255, 227, 132 },
              { 255, 153, 18 },
              { 192, 192, 192 } }

WhiteScreen = Class(object, {
    init = function(self, Layer, time)
        self.lifetime = time or 30
        self.layer = Layer or LAYER.TOP
        self.group = GROUP.GHOST
    end,
    frame = function(self)
        if self.timer >= self.lifetime then
            object.RawDel(self)
        end
    end,
    render = function(self)
        SetImageState("white", "", 255 * (1 - self.timer / self.lifetime), 255, 255, 255)
        RenderRect("white", lstg.world.l, lstg.world.r, lstg.world.b, lstg.world.t)
    end
})

local StageID = { "00", "01", "02", "03", "04", "05", "06", "07", '08', "09", "095", "10", "11", "12", "125", "128", "13", "14", "143", "15", "16", "165", "17", "18", "185" }
for _, p in ipairs(StageID) do
    IncludeLuaFile("mod\\BG\\TH" .. p .. "\\TH" .. p .. "_bg.lua")
    IncludeLuaFile("mod\\GAME\\th" .. p .. ".lua")
end

IncludeLuaFile("mod\\BadApple.lua")
IncludeLuaFile("mod\\music.lua")
IncludeLuaFile("mod\\defachievement.lua")

local cos, sin, max, int, sign = cos, sin, max, int, sign
local bullet, object, boss = bullet, object, boss
local task, ran, misc, sp = task, ran, misc, sp
local table, type = table, type
local GROUP, LAYER = GROUP, LAYER
local New = New
local NewSimpleBullet = NewSimpleBullet
local PlaySound = PlaySound
local IsValid = IsValid
local SetImageState = SetImageState
local Render = Render
local Class = Class

LoadFX("fx:color_set", "shader\\color_set.hlsl")

do

    local _bullet = Class(bullet, {
        frame = function(self)
            if self.frame_new then
                self:frame_new()
            else
                bullet.frame(self)
            end
        end,
        render = function(self)
            if self.render_new then
                self:render_new()
            else
                bullet.render(self)
            end
        end
    })
    ---@param blend number@快速设置高光
    function _bullet:init(imgclass, index, stay, indes, blend, x, y)
        bullet.init(self, imgclass, index, stay, indes)
        self._blend = blend and "mul+add" or self._blend
        self.x, self.y = x, y
        self.autorot = bullet.GetNavi(self)
    end

    SimpleText = Class(object, {
        init = function(self, x, y, layer, text, alpha, color, lifetime, f, viewmode, ...)
            self.x, self.y = x, y
            self.layer = layer or LAYER.TOP
            self.group = GROUP.GHOST
            self.colli = false
            self.bound = false
            self.text = text or ""
            self.alpha = alpha or 0
            self.color = color or { 255, 255, 255 }
            self.other = { ... }
            self.lifetime = lifetime
            self.viewmode = viewmode or "world"
            self.size = 1
            self.type = "sc_menu"
            task.New(self, f or function()
            end)
        end,
        frame = function(self)
            task.Do(self)
            if self.lifetime then
                if self.timer >= self.lifetime then
                    object.RawDel(self)
                end
            end
        end,
        render = function(self)
            SetViewMode(self.viewmode)
            local s = GetImageScale()
            SetImageScale(s * self.size)
            RenderTTF(self.type, self.text, self.x + 1, self.y - 1, Color(self.alpha, 0, 0, 0), unpack(self.other))
            RenderTTF(self.type, self.text, self.x, self.y, Color(self.alpha, unpack(self.color)), unpack(self.other))
            SetImageScale(s)
            SetViewMode("world")
        end
    })
    function SimpleText.MusicSign(text, color)
        New(SimpleText, 190, -260, nil, text, 255, color, nil, function()
            local self = task.GetSelf()
            task.MoveTo(190, -206, 60, 2)
            task.Wait(180)
            task.MoveTo(450, -206, 60, 1)
            object.RawDel(self)
        end, nil, "right")
    end

    global_obj = {}
    local global_obj = global_obj
    --承载着简单事件的简单弹
    global_obj["bullet_decel"] = Class(_bullet, { init = function(self, _x, _y, style, col, fv, v, a, blend, stay)
        _bullet.init(self, style, col, (stay or stay == nil) and true, true, blend, _x, _y)
        self.wait = 0
        self.time = 25
        object.SetV(self, fv, a, self.autorot)
        task.New(self, function()
            task.Wait(self.wait)
            object.ChangingV(self, fv, v, self.rot, self.time, self.autorot)
        end)
    end })
    global_obj["bullet_accel"] = Class(_bullet, { init = function(self, _x, _y, style, col, fv, v, a, blend, stay, wait, time)
        _bullet.init(self, style, col, (stay or stay == nil) and true, true, blend, _x, _y)
        self.wait = wait or 60
        self.time = time or 120
        object.SetV(self, fv, a, self.autorot)
        task.New(self, function()
            task.Wait(self.wait)
            object.ChangingV(self, fv, v, self.rot, self.time, self.autorot)
        end)
    end })
    global_obj["bullet_dec_acc"] = Class(_bullet, { init = function(self, _x, _y, style, col, fv, v, a, blend, stay)
        _bullet.init(self, style, col, (stay or stay == nil) and true, true, blend, _x, _y)
        self.time1, self.time2, self.time3 = 25, 60, 120
        object.SetV(self, fv, a, self.autorot)
        task.New(self, function()
            object.ChangingV(self, fv, 0.5, self.rot, self.time1, self.autorot)
            task.Wait(self.time2)
            object.ChangingV(self, 0.5, v, self.rot, self.time3, self.autorot)
        end)
    end })
    global_obj["bullet_dec_setangle"] = Class(_bullet, { init = function(self, _x, _y, sty, col, ...)
        local c = { ... }
        local t = true
        if type(c[1]) == "boolean" then
            t = c[1]
            table.remove(c, 1)
        end
        _bullet.init(self, sty, col, t, true, false, _x, _y)
        object.SetV(self, c[1].v, c[1].a, self.autorot)
        task.New(self, function()
            for i, con in ipairs(c) do
                if con.v then
                    object.SetV(self, con.v, con.a, self.autorot)
                end
                if con.func then
                    con.func(self)
                end
                PlaySound("kira00", 0.2, self.x / 256, true)
                if i == #c then
                    break
                end
                if con.v then
                    object.ChangingV(self, con.v, 0, con.a, int(con.time or 0), self.autorot, 5)
                end
                task.Wait(con.wait or 0)
            end
        end)
    end })
    global_obj["bullet_changeangle"] = Class(_bullet, { init = function(self, _x, _y, sty, col, v, a, ...)
        local c = { ... }
        local t = true
        if type(c[1]) == "boolean" then
            t = c[1]
            table.remove(c, 1)
        end
        _bullet.init(self, sty, col, t, true, false, _x, _y)
        self.angle = a
        self.v = v
        object.SetV(self, v, self.angle, self.autorot)
        task.New(self, function()
            local _v
            for _, con in ipairs(c) do
                task.Wait(con.wait or 0)
                _v = -self.v + (con.v or self.v)
                con.r = con.r or 0
                for _ = 1, con.time do
                    self.v = self.v + _v / con.time
                    self.angle = self.angle + con.r
                    object.SetV(self, self.v, self.angle, self.autorot)
                    task.Wait()
                end
            end
            self.changed = true
        end)
    end })
    global_obj["bullet_setvxvy"] = Class(_bullet, { init = function(self, _x, _y, sty, col, vx, vy, stay)
        _bullet.init(self, sty, col, (stay or stay == nil) and true, true, false, _x, _y)
        self.vx = vx
        self.vy = vy
        self.navi = true
    end })
    global_obj["bullet_create_eff"] = Class(_bullet, { init = function(self, _x, _y, sty, col, v, a, blend)

        self.colli = false
        if type(_x) == "table" then
            _bullet.init(self, _x.imgclass, _x._index, false, true, false, _x.x, _x.y)
            self.group = 0
            self._blend = _x._blend
            task.New(self, function()
                for _ = 1, 11 do
                    if not IsValid(_x) then
                        break
                    end
                    self.x, self.y = _x.x, _x.y
                    task.Wait()
                end
                object.RawDel(self)
            end)
        else
            _bullet.init(self, sty, col, false, true, blend, _x, _y)
            self.group = 0
            if v and a then
                object.SetV(self, v, a, self.autorot)
            end
            task.New(self, function()
                task.Wait(11)
                object.RawDel(self)
            end)
        end

    end })
    local rand = math.random
    global_obj["little_charge_out"] = Class(_object, {
        leaf_insert = function(self, l, angle, lifetime, size)
            table.insert(self.leaf, {
                x = self.x,
                y = self.y,
                v = l / lifetime,
                a = angle + 180,
                timer = 0,
                lifetime = lifetime,
                size = size,
                hscale = size,
                vscale = size,
                _d_size = -(1 + rand() * 2) * size / lifetime,
                alpha = 125,
                rot = rand() * 360,
                omiga = (0.8 + rand() * 0.4) * ({ 1, -1 })[rand(2)]
            })
        end,
        init = function(self, _x, _y, a, r, g, b, s)
            self.x, self.y = _x, _y
            self.img = "circle_charge"
            self.layer = LAYER.ENEMY + 50
            self.group = GROUP.GHOST
            self.hide = false
            self.bound = true
            self.navi = false
            self.hp = 10
            self.maxhp = 10
            self.colli = true
            self._servants = {}
            self._blend, self._a, self._r, self._g, self._b = 'mul+add', 255, r, g, b
            self.leaf = {}
            task.New(self, function()
                PlaySound("enep00", 0.2, 0, false)
                local _s = 0
                local _a = a
                for i = 1, 30 do
                    if i < 15 then
                        self.class.leaf_insert(self, 150 + rand() * 50, rand() * 360, rand(40, 70), rand() * 0.7 + 0.8)
                        self.class.leaf_insert(self, 200 + rand() * 100, rand() * 360, rand(40, 70), rand() * 0.7 + 0.8)
                    end
                    self.hscale = _s
                    self.vscale = _s
                    self._a = _a
                    task.Wait()
                    _s = _s + s / 29
                    _a = _a - a / 29
                end
                while #self.leaf > 0 do
                    task.Wait()
                end
                object.Del(self)
            end)
        end,
        frame = function(self)
            _object.frame(self)
            local l
            for i = #self.leaf, 1, -1 do
                l = self.leaf[i]
                l.x = l.x + cos(l.a) * l.v
                l.y = l.y + sin(l.a) * l.v
                l.size = l.size + l._d_size
                l.hscale = l.size
                if l.timer > l.lifetime - 15 then
                    l.alpha = max(0, 125 * (l.lifetime - l.timer - 1) / 15)
                end
                if l.timer == l.lifetime then
                    table.remove(self.leaf, i)
                end
                l.timer = l.timer + 1
            end
        end,
        render = function(self)
            _object.render(self)
            for _, l in ipairs(self.leaf) do
                SetImageState("circle_charge_eff", "mul+add", max(l.alpha, 0), 255, 255, 255)
                Render("circle_charge_eff", l.x, l.y, l.rot, l.hscale, l.vscale)
            end
        end
    })
    global_obj["leaf_eff"] = Class(object, {
        init = function(self, x, y, v, a, lifetime, size, r, g, b)
            self.img = "circle_charge_eff"
            self.x, self.y = x, y
            self.rot = ran:Float(0, 360)
            self.omiga = ran:Float(0.8, 1.2) * ran:Sign()
            self.hscale = size
            self.vscale = size
            self.layer = LAYER.TOP + 50
            self.group = GROUP.GHOST
            self.size = size
            self.v = v
            self.angle = a
            self.lifetime = lifetime
            self._x, self._y = x, y
            self.r, self.g, self.b = r, g, b
            self._s = ran:Float(1, 3)
        end,
        frame = function(self)
            if self.timer >= self.lifetime then
                object.Del(self)
                self.hide = true
            end
            local s = self.size + (-self._s * self.size / self.lifetime) * (self.timer - 1)
            local i = 0 + (90 / self.lifetime) * (self.timer - 1)
            local l = self.v * self.lifetime
            self.x = self._x + l * cos(self.angle) * sin(i)
            self.y = self._y + l * sin(self.angle) * sin(i)
            self.hscale = s
        end,
        render = function(self)
            local alpha = 125 - 125 + 125 * sin(90 - self.timer / self.lifetime * 90)
            SetImageState(self.img, 'mul+add', max(0, alpha), self.r, self.g, self.b)
            Render(self.img, self.x, self.y, self.rot, self.hscale, self.vscale)
        end
    })
    global_obj["saoqi_wave"] = Class(object, {
        init = function(self, _x, _y, rot, bb, s, r, g, b)
            self.x, self.y = _x, _y
            self.img = "saoqi2"
            self.layer = LAYER.ENEMY - 2
            self.group = GROUP.GHOST
            self.bound = false
            self._blend, self._a, self._r, self._g, self._b = 'mul+add', 0, r, g, b
            self.rot = rot
            self.hscale = 0
            self.vscale = 0
            self.alpha = 0
            self.boss = bb
            self.rr = r
            self.bb = b
            self.gg = g
            task.New(self, function()
                for i = 1, 60 do
                    self.hscale = 2 + (-2 + s) / 60 * i
                    self.vscale = self.hscale
                    task.Wait()
                end
            end)
        end,
        frame = function(self)
            task.Do(self)
            if IsValid(self.boss) then
                self.x = self.boss.x
                self.y = self.boss.y
            end
            if self.timer >= 60 then
                object.Del(self)
            end
            if self.timer <= 15 then
                self._a = self._a + 255 * 0.5 / 15
            end
            self._a = self._a - 255 * 0.5 / 60
        end,
        render = function(self)
            _object.render(self)
        end
    })

    global_obj["laser_line"] = Class(laser, {
        init = function(self, x, y, col, v, a, GrowTime, Width, Count, Head, nosound)
            laser.init(self, col, x, y, a, 0, 0, 0, Width or 8, Width or 8, Head or 0)
            laser.CyGrow(self, v, GrowTime, Count or 5, a, nosound)
        end,
        frame = function(self)
            if self.frame_new then
                self.frame_new(self)
            else
                laser.frame(self)
            end
        end,
        render = function(self)
            if self.render_new then
                self.render_new(self)
            else
                laser.render(self)
            end
        end
    })
    global_obj["laser_changeangle"] = Class(bent_laser, { init = function(self, x, y, index, l, w, v, a, ...)
        bent_laser.init(self, index, x, y, l, w, 4, w)
        PlaySound("lazer00", 0.1, self.x / 100)
        self.angle = a
        self.v = v
        object.SetV(self, v, self.angle, true)
        local c = { ... }
        task.New(self, function()
            local _v
            for _, con in ipairs(c) do
                task.Wait(con.wait or 0)
                _v = con.v or self.v
                con.r = con.r or 0
                for t = 1, con.time do
                    self.v = self.v + (-self.v + _v) / con.time * t--奇怪的不想修复的算法
                    self.angle = self.angle + con.r
                    object.SetV(self, self.v, self.angle, true)
                    task.Wait()
                end
            end
        end)
    end })

    sakura_big = Class(bullet, {
        init = function(self, x, y, a, o, vx, vy)
            bullet.init(self, sakura, 4, false, true)
            self.mx, self.my = x, y
            self.rot = a
            self.x, self.y = self.mx + cos(self.rot + 180) * 8, self.my + sin(self.rot + 180) * 8
            self.omiga = o
            self.mvx, self.mvy = vx, vy
            self.max, self.may = 0, 0
        end,
        frame = function(self)
            bullet.frame(self)
            self.x, self.y = self.mx + cos(self.rot + 180) * 8, self.my + sin(self.rot + 180) * 8
            self.mx, self.my = self.mx + self.mvx, self.my + self.mvy
            self.mvx, self.mvy = self.mvx + self.max, self.mvy + self.may
        end
    })
    function sakura_big.New(x, y, fa, fo, v, a, func)
        local b
        for i = 1, 5 do
            b = New(sakura_big, x, y, fa + i * 72, fo, v * cos(a), v * sin(a))
            if func then
                func(b)
            end
        end
    end
    Create = {
        bullet_decel = function(x, y, style, col, fv, v, a, blend, stay)
            return New(global_obj["bullet_decel"], x, y, style, col, fv, v, a, blend, stay)
        end,
        bullet_accel = function(x, y, style, col, fv, v, a, blend, stay, wait, time)
            return New(global_obj["bullet_accel"], x, y, style, col, fv, v, a, blend, stay, wait, time)
        end,
        bullet_dec_acc = function(x, y, style, col, fv, v, a, blend, stay)
            return New(global_obj["bullet_dec_acc"], x, y, style, col, fv, v, a, blend, stay)
        end,
        bullet_dec_setangle = function(x, y, sty, col, ...)
            return New(global_obj["bullet_dec_setangle"], x, y, sty, col, ...)
        end,
        bullet_changeangle = function(x, y, sty, col, v, a, ...)
            return New(global_obj["bullet_changeangle"], x, y, sty, col, v, a, ...)
        end,
        bullet_setvxvy = function(x, y, sty, col, vx, vy, stay)
            return New(global_obj["bullet_setvxvy"], x, y, sty, col, vx, vy, stay)
        end,
        bullet_create_eff = function(x, y, sty, col, v, a, blend)
            return New(global_obj["bullet_create_eff"], x, y, sty, col, v, a, blend)
        end,
        little_charge_out = function(x, y, a, r, g, b, size)
            return New(global_obj["little_charge_out"], x, y, a, r, g, b, size)
        end,
        leaf_eff = function(x, y, v, a, lifetime, size, r, g, b)
            return New(global_obj["leaf_eff"], x, y, v, a, lifetime, size, r, g, b)
        end,
        saoqi_wave = function(x, y, rot, master, size, r, g, b)
            return New(global_obj["saoqi_wave"], x, y, rot, master, size, r, g, b)
        end,
        laser_line = function(x, y, col, v, a, GrowTime, Width, Scale, Head, nosound)
            return New(global_obj["laser_line"], x, y, col, v, a, GrowTime, Width, Scale, Head, nosound)
        end,
        laser_changeangle = function(x, y, index, l, w, v, a, ...)
            return New(global_obj["laser_changeangle"], x, y, index, l, w, v, a, ...)
        end
    }
end--通用物

function SmearScreen(self, lifetime, time, inclt, maxlt, del_immediately)
    inclt = inclt or 0
    maxlt = maxlt or 9999
    task.New(self, function()
        local _uv1, _uv2, _uv3, _uv4 = { [3] = 0.5 }, { [3] = 0.5 }, { [3] = 0.5 }, { [3] = 0.5 }
        local w = lstg.world
        _uv1[1], _uv1[2] = w.l, w.t
        _uv2[1], _uv2[2] = w.r, w.t
        _uv3[1], _uv3[2] = w.r, w.b
        _uv4[1], _uv4[2] = w.l, w.b
        _uv1[4], _uv1[5] = WorldToScreen(w.l, w.t)
        _uv2[4], _uv2[5] = WorldToScreen(w.r, w.t)
        _uv3[4], _uv3[5] = WorldToScreen(w.r, w.b)
        _uv4[4], _uv4[5] = WorldToScreen(w.l, w.b)
        local objs = {}
        local maxk = 1
        local k = 1
        for i = 1, time do
            local name = "SmearScreen_EFF" .. k
            CreateRenderTarget(name)
            table.insert(objs, New(Class(object, {
                init = function(unit)
                    unit.layer = LAYER.BG - 10
                    unit.colli = false
                end,
                frame = function(unit)
                    if unit.timer >= lifetime then
                        Del(unit)
                    end
                end,
                render = function(unit)
                    if unit.timer == 1 and lifetime >= 1 then
                        PushRenderTarget(name)
                        RenderClear(Color(0, 0, 0, 0))
                    end
                end
            }, true)))
            table.insert(objs, New(Class(object, {
                init = function(unit)
                    unit.layer = LAYER.TOP - 1 - i * 0.01
                    unit.colli = false
                end,
                frame = function(unit)
                    if unit.timer >= lifetime then
                        Del(unit)
                    end
                end,
                render = function(unit)
                    if lifetime >= 1 then
                        if unit.timer == 1 then
                            PopRenderTarget(name)
                        end
                        local _color = Color(max(1 - (unit.timer - 1) / lifetime, 0) * 255, 255, 255, 255)
                        _uv1[6] = _color
                        _uv2[6] = _color
                        _uv3[6] = _color
                        _uv4[6] = _color
                        RenderTexture(name, "mul+add", _uv1, _uv2, _uv3, _uv4)
                    end
                end
            }, true)))

            lifetime = min(lifetime + inclt, maxlt)
            k = k + 1
            if i % (lifetime + 1) == 0 then
                k = 1
            end
            maxk = max(maxk, k)
            task.Wait()
        end
        if del_immediately then
            sp:UnitListUpdate(objs)
            for _, o in ipairs(objs) do
                object.RawDel(o)
            end
        else
            task.Wait(lifetime)
        end
        for i = 1, maxk do
            RemoveResource("stage", 1, "SmearScreen_EFF" .. i)
        end
    end)
end

function SmearScreen2(self, lifetime, time, inclt, maxlt, del_immediately)
    inclt = inclt or 0
    maxlt = maxlt or 9999
    task.New(self, function()
        local _uv1, _uv2, _uv3, _uv4 = { [3] = 0.5 }, { [3] = 0.5 }, { [3] = 0.5 }, { [3] = 0.5 }
        local w = lstg.world
        _uv1[1], _uv1[2] = w.l, w.t
        _uv2[1], _uv2[2] = w.r, w.t
        _uv3[1], _uv3[2] = w.r, w.b
        _uv4[1], _uv4[2] = w.l, w.b
        _uv1[4], _uv1[5] = WorldToScreen(w.l, w.t)
        _uv2[4], _uv2[5] = WorldToScreen(w.r, w.t)
        _uv3[4], _uv3[5] = WorldToScreen(w.r, w.b)
        _uv4[4], _uv4[5] = WorldToScreen(w.l, w.b)
        local objs = {}
        local pop_objs = {}
        local k = 1
        New(Class(object, {
            init = function(unit)
                unit.layer = LAYER.TOP - 1 + 0.01
                unit.colli = false
            end,
            frame = function(unit)
                if unit.timer >= time + lifetime then
                    Del(unit)
                end
            end,
            render = function()
                sp:UnitListUpdate(pop_objs)
                for _, p in ipairs(pop_objs) do
                    RenderTexture(p.name, "", _uv1, _uv2, _uv3, _uv4)
                end
            end
        }, true))
        for i = 1, time do
            local name = "SmearScreen2_EFF" .. k
            CreateRenderTarget(name)
            local push = New(Class(object, {
                init = function(unit)
                    unit.layer = LAYER.BG - 10
                    unit.colli = false
                end,
                frame = function(unit)
                    if unit.timer >= lifetime then
                        Del(unit)
                    end
                end,
                render = function(unit)
                    if unit.timer == 1 and lifetime >= 1 then
                        PushRenderTarget(name)
                        RenderClear(Color(0, 0, 0, 0))
                    end
                end
            }, true))
            local pop = New(Class(object, {
                init = function(unit)
                    unit.layer = LAYER.TOP - 1 - i * 0.01
                    unit.colli = false
                    unit.name = name
                end,
                frame = function(unit)
                    if unit.timer >= lifetime then
                        Del(unit)
                    end
                end,
                render = function(unit)
                    if lifetime >= 1 then
                        if unit.timer == 1 then
                            PopRenderTarget(name)

                        end
                        local _color = Color(max(1 - (unit.timer - 1) / lifetime, 0) * 255, 255, 255, 255)
                        _uv1[6] = _color
                        _uv2[6] = _color
                        _uv3[6] = _color
                        _uv4[6] = _color
                        RenderTexture(name, "", _uv1, _uv2, _uv3, _uv4)
                    end
                end
            }, true))
            table.insert(objs, push)
            table.insert(objs, pop)
            table.insert(pop_objs, pop)
            lifetime = min(lifetime + inclt, maxlt)
            k = k + 1
            if i % (lifetime + 1) == 0 then
                k = 1
            end
            task.Wait()
        end
        if del_immediately then
            sp:UnitListUpdate(objs)
            for _, o in ipairs(objs) do
                object.RawDel(o)
            end
        end
    end)
end

---一种新的创建obj的方式
---创建后自行用函数对他操作
---测试ing
function NewObject(base_class)
    local obj = New(object)
    obj.class = base_class
    return obj
end

local wave = Class(object, {
    init = function(unit, x, y, w, sr, time, r, g, b)
        unit.x, unit.y = x, y
        unit.layer = 1
        unit.group = GROUP.INDES
        unit.w = w
        unit.sr = sr
        unit.time = time
        unit.nr = 0
        unit.smear = {}
        unit.alpha = 255
        unit.colli = false
        unit._r, unit._g, unit._b = r or 255, g or 255, b or 255
    end,
    frame = function(unit)

        unit.lr = unit.nr
        unit.alpha = max(0, 255 * (1 - unit.timer / unit.time))
        unit.nr = task.SetMode[2](unit.timer / unit.time) * unit.sr
        if unit.timer > unit.time then
            if #unit.smear == 0 then
                Del(unit)
            end
        else
            table.insert(unit.smear, { alpha = unit.alpha / 2, r = unit.nr, w = (unit.nr - unit.lr) })
        end
        local s
        for i = #unit.smear, 1, -1 do
            s = unit.smear[i]
            s.alpha = max(s.alpha - 15, 0)
            if s.alpha == 0 then
                table.remove(unit.smear, i)
            end
        end
    end,
    render = function(unit)
        SetImageState("white", "mul+add", unit.alpha, unit._r, unit._g, unit._b)
        misc.SectorRender(unit.x, unit.y, unit.nr - unit.w / 2, unit.nr + unit.w / 2, 0, 360, 80)
        for _, s in ipairs(unit.smear) do
            SetImageState("white", "mul+add", s.alpha, unit._r, unit._g, unit._b)
            misc.SectorRender(unit.x, unit.y, s.r - s.w, s.r, 0, 360, 80)
        end
    end
})
local bon = Class(object, {
    init = function(self, x, y, time, radius, r, g, b)
        self.x, self.y = x, y
        self.layer = LAYER.ENEMY + 1
        self.group = GROUP.INDES
        self.colli = false
        self.lifetime = time
        self.r = radius
        self.alpha = 1
        self._r, self._g, self._b = r, g, b
        self.particle = {}
        for _ = 1, 30 do
            local a = ran:Float(0, 360)
            local v = ran:Float(3, 6)
            table.insert(self.particle, {
                x = self.x, y = self.y,
                vx = cos(a) * v, vy = sin(a) * v,
                alpha = ran:Float(150, 250), timer = 0,
            })
        end
        task.New(self, function()
            task.SmoothSetValueTo("alpha", 0, time, 0)
        end)
    end,
    frame = function(self)
        task.Do(self)
        local p
        local maxtime = max(10, self.lifetime - 20)
        for i = #self.particle, 1, -1 do
            p = self.particle[i]
            p.x = p.x + p.vx
            p.y = p.y + p.vy
            p.vx = p.vx - p.vx * 0.04
            p.vy = p.vy - p.vy * 0.04
            if p.timer > maxtime then
                p.alpha = max(p.alpha - 5, 0)
                if p.alpha == 0 then
                    table.remove(self.particle, i)
                end
            end
            p.timer = p.timer + 1
        end
        if self.timer >= self.lifetime and #self.particle == 0 then
            object.Del(self)
        end
    end,
    render = function(self)
        for _, p in ipairs(self.particle) do
            SetImageState("bright", "mul+add", p.alpha, self._r, self._g, self._b)
            Render("bright", p.x, p.y, 0, 8 / 150)
        end
        if self.alpha > 0 then
            SetImageState("bright", "mul+add", self.alpha * 255, self._r, self._g, self._b)
            Render("bright", self.x, self.y, 0, self.r / 75)
        end
    end
})
function NewBon(x, y, time, radius, r, g, b)
    return New(bon, x, y, time, radius, r, g, b)
end
function NewWave(x, y, width, maxr, time, r, g, b)
    return New(wave, x, y, width, maxr, time, r, g, b)
end

local EFF_BRIGHTPILLAR = Class(object, {
    init = function(self, time, x, y, rot, width, Hue, alpha, event)
        self.rx, self.ry = 0, 0
        self.rot = rot
        self.x, self.y = x, y
        self.width = width
        self.layer = LAYER.BG + 10
        self.group = GROUP.GHOST
        self.alpha = 0
        self.bound = false
        self.Hue = Hue
        self.linew = 1
        self.S = 0.4
        self.V = 1
        if event then
            event(self)
        end
        task.New(self, function()
            for i = 1, 90 do
                self.alpha = alpha * sin(i)
                task.Wait()
            end
            task.Wait(time - 135)
            for i = 1, 45 do
                self.alpha = alpha - alpha * sin(i * 2)
                task.Wait()
            end
            Del(self)
        end)
    end,
    frame = function(self)
        task.Do(self)
    end,
    render = function(self)
        local r, g, b = sp:HSVtoRGB(self.Hue, self.S, self.V)
        OriginalSetImageState("white", "mul+add",
                Color(self.alpha * 255, r, g, b),
                Color(self.alpha * 255, r, g, b),
                Color(0, r, g, b), Color(0, r, g, b))
        local w = self.width / 2 - self.linew
        Render("white",
                self.x + cos(self.rot + 90) * w,
                self.y + sin(self.rot + 90) * w,
                self.rot + 180, 100, self.width / 16)
        Render("white",
                self.x + cos(self.rot - 90) * w,
                self.y + sin(self.rot - 90) * w,
                self.rot, 100, self.width / 16)
    end
}, true)
_editor_class.EFF_BRIGHTPILLAR = EFF_BRIGHTPILLAR

local EFF_BRIGHTLINE = Class(object, {
    init = function(self, time, x, y, rot, width, length, Hue, alpha, event)
        self.rx, self.ry = 0, 0
        self.rot = rot
        self.x, self.y = x, y
        self.width = width
        self.layer = LAYER.BG + 10
        self.group = GROUP.GHOST
        self.alpha = 0
        self.bound = false
        self.Hue = Hue
        self.S = 0.4
        self.V = 1
        self.length = length
        if event then
            event(self)
        end
        task.New(self, function()
            for i = 1, 90 do
                self.alpha = alpha * sin(i)
                task.Wait()
            end
            task.Wait(time - 135)
            for i = 1, 45 do
                self.alpha = alpha - alpha * sin(i * 2)
                task.Wait()
            end
            Del(self)
        end)
    end,
    frame = function(self)
        task.Do(self)
    end,
    render = function(self)
        SetImageState("bright_line", "mul+add", self.alpha * 255, sp:HSVtoRGB(self.Hue, self.S, self.V))
        Render("bright_line", self.x, self.y, self.rot, self.length / 200, self.width / 32)
    end
}, true)
_editor_class.EFF_BRIGHTLINE = EFF_BRIGHTLINE

local PointRender = Class(object, {
    init = function(self, point, lifetime, a, r, g, b, noclose, layer)
        object.init(self, 0, 0, 0, layer or LAYER.ENEMY_BULLET - 1)
        self.point = point
        self.lifetime = lifetime
        self._a = a
        self._r, self._g, self._b = r, g, b
        self.close = not noclose
        self.update = true
    end,
    frame = function(self)
        task.Do(self)
        if self.timer >= self.lifetime then
            Del(self)
        end
    end,
    render = function(self)
        SetImageState("white", "mul+add", self._a, self._r, self._g, self._b)
        if self.update then
            sp:UnitListUpdate(self.point)
        end
        misc.RenderPointLine("white", self.point, 1, self.close)
    end
})
_editor_class.PointRender = PointRender

local PASS_CONTROL_UNIT
---咏唱解除机制
local function ForcePassSpell(open)
    if IsValid(PASS_CONTROL_UNIT) then
        Del(PASS_CONTROL_UNIT)
    end
    if open then
        PASS_CONTROL_UNIT = New(Class(object, {
            frame = task.Do,
            init = function(self)
                self.layer = LAYER.PLAYER - 1
                self.group = GROUP.GHOST
                self.alpha = 0
                task.New(self, function()
                    while true do
                        if player.death >= 89 then
                            lstg.var.dead = lstg.var.dead - 1
                            player.lock = true
                            for _, b in ipairs(boss_group) do
                                task.Clear(b)
                            end
                            for i = 1, 60 do
                                for bgm in pairs(ext.music) do
                                    SetBGMVolume(bgm, 1 - i / 60)
                                end
                                for _, b in ipairs(boss_group) do
                                    b.timer = b.timer - 1
                                end
                                self.alpha = i / 60
                                task.Wait()
                            end
                            local t = boss_group[1].t1 - boss_group[1].timer - 60
                            for bgm, p in pairs(ext.music) do
                                p.timer = p.timer + t
                                SetBGMVolume(bgm, 1)
                            end
                            for _ = 1, t do
                                task.Do(stage.current_stage)
                            end
                            task.New(self, function()
                                for i = 59, 0, -1 do
                                    self.alpha = i / 60
                                    task.Wait()
                                end
                            end)
                            ext.FastMusic()
                            New(WhiteScreen)
                            for _, b in ipairs(boss_group) do
                                object.Kill(b)
                            end
                            player.lock = false
                        end
                        task.Wait()
                    end
                end)
            end,
            render = function(self)
                local b = min(self.timer / 90, 1)
                for i = 1, 16 do
                    SetImageState('bossring3' .. i, "add+add", b * 150, sp:HSVtoRGB(35, 0.9, 1))
                end
                local t = task.SetMode[2](self.alpha)
                misc.RenderRing('bossring3', player.x, player.y, 150 + t * 100, 190 + t * 100, self.timer * 2, 48, 16)
                SetImageState("Sakura2", "mul+add", t * 200, 250, 128, 114)
                Render("Sakura2", player.x, player.y, self.timer * 2, 1 - t * 0.3)
            end
        }, true))
    end
end
_G.ForcePassSpell=ForcePassSpell

local PulseScreen = Class(object, {
    init = function(self, layer, col, blend, fade_in, stay, fade_out, mode)
        self.layer = layer or LAYER.TOP
        self.group = GROUP.GHOST
        self.blend = blend or ""
        self.mode = mode or "world"
        self._r, self._g, self._b = unpack(col or { 255, 255, 255 })
        fade_in = fade_in or 0
        stay = stay or 0
        fade_out = fade_out or 0
        self.lifetime = fade_in + stay + fade_out
        if fade_in > 0 then
            self._a = 0
        else
            self._a = 255
        end
        task.New(self, function()
            for i = 1, fade_in do
                self._a = i / fade_in * 255
                task.Wait()
            end
            task.Wait(stay)
            for i = 1, fade_out do
                self._a = 255 - i / fade_out * 255
                task.Wait()
            end
        end)

    end,
    frame = function(self)
        task.Do(self)
        if self.timer >= self.lifetime then
            object.RawDel(self)
        end
    end,
    render = function(self)
        SetImageState("white", self.blend, self._a, self._r, self._g, self._b)
        if self.mode == "world" then
            RenderRect("white", lstg.world.l, lstg.world.r, lstg.world.b, lstg.world.t)
        else
            RenderRect("white", 0, screen.width, 0, screen.height)
        end
    end
})
function NewPulseScreen(layer, col, blend, fade_in, stay, fade_out, mode)
    return New(PulseScreen, layer, col, blend, fade_in, stay, fade_out, mode)
end

local SimpleServant = Class(object)
function SimpleServant:init(x, y, a, r, g, b, scale, event, frame)
    object.init(self, x, y, GROUP.INDES, LAYER.ENEMY)
    self.colli = false
    self.img = "servant"
    self.frame_func = frame or load("")
    self._a, self._r, self._g, self._b = a, r, g, b
    self._blend = "mul+add"
    self.hscale = scale
    self.vscale = scale
    self.omiga = ran:Float(2, 3) * ran:Sign()
    function self:FadeIn(time, mode)
        task.New(self, function()
            local nowa = self._a
            mode = mode or 0
            for i = 1, time do
                self._a = nowa + (255 - nowa) * task.SetMode[mode](i / time)
                task.Wait()
            end
        end)
    end
    function self:FadeOut(time, mode)
        task.New(self, function()
            local nowa = self._a
            mode = mode or 0
            for i = 1, time do
                self._a = nowa * task.SetMode[mode](1 - i / time)
                task.Wait()
            end
        end)
    end
    if event then
        event(self)
    end
end
function SimpleServant:frame()
    task.Do(self)
    self:frame_func()
end
function SimpleServant:render()
    SetImageState(self.img, self._blend, self._a, self._r, self._g, self._b)
    DefaultRenderFunc(self)
end
_G.SimpleServant = SimpleServant
function NewSimpleServant(x, y, a, r, g, b, scale, event, frame)
    return New(SimpleServant, x, y, a, r, g, b, scale, event, frame)
end

function ParticleLaserBent(pR, pG, pB, x, y, index, length, w, v, a, ...)
    local l = Create.laser_changeangle(x, y, index, length, w, v, a, ...)
    l.particle = {}
    l.pcol = { pR, pG, pB }
    function l:frame_new()
        bent_laser.frame(self)
        if self.timer < 90 then
            local _a = ran:Float(0, 360)
            local _v = ran:Float(3, 6)
            table.insert(self.particle, {
                x = self.x, y = self.y,
                vx = cos(_a) * _v, vy = sin(_a) * _v,
                alpha = ran:Float(200, 250), timer = 0,
                r = self.pcol[1], g = self.pcol[2], b = self.pcol[3]
            })
        end
        local p
        for i = #self.particle, 1, -1 do
            p = self.particle[i]
            p.x = p.x + p.vx
            p.y = p.y + p.vy
            p.vx = p.vx - p.vx * 0.04
            p.vy = p.vy - p.vy * 0.04
            if p.timer > 10 then
                p.alpha = max(p.alpha - 5, 0)
                if p.alpha == 0 then
                    table.remove(self.particle, i)
                end
            end
            p.timer = p.timer + 1
        end
        self.bound = (#self.particle == 0) and (self.timer > 30)

    end
    function l:render_new()
        bent_laser.render(self)
        for _, p in ipairs(self.particle) do
            SetImageState("bright", "mul+add", p.alpha, p.r, p.g, p.b)
            Render("bright", p.x, p.y, 0, 10 / 150)
        end
    end
    return l
end
function ParticleLaserLine(pR, pG, pB, x, y, col, v, a, GrowTime, Width, Scale, Head, nosound)
    local l = Create.laser_line(x, y, col, v, a, GrowTime, Width, Scale, Head, nosound)
    l.particle = {}
    l.pcol = { pR, pG, pB }
    function l:frame_new()
        laser.frame(self)
        local len = self.l1 + self.l2 + self.l3
        local hx, hy = self.x + cos(self.rot) * len, self.y + sin(self.rot) * len
        if self.timer < 90 then
            local _a = ran:Float(0, 360)
            local _v = ran:Float(3, 6)
            table.insert(self.particle, {
                x = hx, y = hy,
                vx = cos(_a) * _v, vy = sin(_a) * _v,
                alpha = ran:Float(200, 250), timer = 0,
                r = self.pcol[1], g = self.pcol[2], b = self.pcol[3]
            })
        end
        local p
        for i = #self.particle, 1, -1 do
            p = self.particle[i]
            p.x = p.x + p.vx
            p.y = p.y + p.vy
            p.vx = p.vx - p.vx * 0.04
            p.vy = p.vy - p.vy * 0.04
            if p.timer > 10 then
                p.alpha = max(p.alpha - 5, 0)
                if p.alpha == 0 then
                    table.remove(self.particle, i)
                end
            end
            p.timer = p.timer + 1
        end
        self.bound = (#self.particle == 0) and (self.timer > 30)

    end
    function l:render_new()
        laser.render(self)
        for _, p in ipairs(self.particle) do
            SetImageState("bright", "mul+add", p.alpha, p.r, p.g, p.b)
            Render("bright", p.x, p.y, 0, 10 / 150)
        end
    end
    return l
end

for t = 1, 25 do
    table.insert(LoadRes, function()
        LoadTexture(("stage_pic%d"):format(t), ("mod\\GAME\\stage_pic%d.png"):format(t))
        LoadImage(("stage_pic%d"):format(t), ("stage_pic%d"):format(t), 0, 0, 512, 512)
    end)
end

---开发者模式
if FileExist("Creative.lua") then
    DoFile("Creative.lua")
end

IncludeLuaFile("mod\\main_stage.lua")
IncludeLuaFile("mod\\summary.lua")

IncludeLuaFile("mod\\th16AEX\\root.lua")